
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      runAsUser: 0 # root
      readOnlyRootFilesystem: false