apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: myuser
spec:
  request: <base64-encoded-csr>
  signerName: kubernetes.io/kubelet-serving
  expirationSeconds: 86400  # one day
  usages:
  - client auth
  - digital signature
  - key encipherment
  - server auth 