apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ingress-tls
data:
  tls.crt: |
    <base64-encoded cert data from tls-ingress.crt>
  tls.key: |
    <base64-encoded cert data from tls-ingress.key>
